### ISSUE TITLE
Some missing entries

### ISSUE THREAD

**Issue by angoca** [osmlab/awesome-openstreetmap#41]
These are some missing entries:

# Terrain tools

* FieldsPapers

# Mobile Maps

* Maps.ME

# JavaScript

* Leaflet
* OpenLayers

# Learn websites

* TeachOSM

**Comment by Unkn0wnCat** [comment]
Hey @angoca,

Thanks for your suggestions! FieldsPapers, Leaflet, OpenLayers, and TeachOSM are great additions.
I am a bit hesitant about adding Maps.ME however, as we already have Organic Maps, which very similar to Maps.ME, as it was made by some of the original Maps.ME creators.

Do you think Maps.ME is different enough to be listed anyways?

**Comment by angoca** [comment]
Hi Kevin,

Well, I am not sure what is your criteria to select a project to be or not to be on the list. In the header, it says "projects using OpenStreetMap data for creative purposes, as well as projects dedicated to improving OpenStreetMap". IMHO, according to this sentence, Maps.ME could fit.

Anyway, It is up to you. However, as we dig into this OSM space, you will find many more projects, and probably you will need to create more specific ones.

On another side, this is another source of projects you can include many of them in this list: https://osm-apps.zottelig.ch/

And the last thing, thank you for this list. This kind of curated content lacks in the OSM world. I hope you keep working in this to continuously improve it, and remove the dead projects.

**Comment by Unkn0wnCat** [comment]
Hey Andres,

there are no clear cut criteria, I'm just trying to work together with everyone to build a high-quality list. This is why I didn't outright deny adding Maps.ME to the list, but asked if you think it is different enough. I think I'll create a discussion topic about adding Maps.ME to invite comments from others.

I'll look at the list you've sent, it seems to contain a lot of interesting projects, but it'll take some time to go through.

And last but not least, thank you for being part of the community and sending in suggestions! There are so many amazing projects out there I only learn about because others send them in :p

**Comment by Unkn0wnCat** [comment]
The Maps.ME discussion will now be tracked in #42 and the list you posted will be tracked in #43.

I'll have the other projects in a PR in a few minutes :)

Thanks for your additions! 😃
